# Generated by Django 5.2.13 on 2026-04-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='OrderTransaction',
        ),
        migrations.RenameIndex(
            model_name='ordertransaction',
            new_name='trading_ord_created_a1aabd_idx',
            old_name='trading_tra_created_c8c435_idx',
        ),
    ]
